server {
    listen 80;
    server_name localhost;

    # ESTA ES LA LÍNEA CLAVE QUE DEBEMOS CORREGIR
    root /usr/share/nginx/html;
    
    index index.html;

    location / {
        # Esto es vital para que Angular gestione las rutas y no dé 404 al refrescar
        try_files $uri $uri/ /index.html;
    }

    # Para asegurar que los assets (logos, videos) se carguen bien
    location /assets/ {
        root /usr/share/nginx/html;
    }
}